version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./src/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
